version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: beastmovies-postgres
    environment:
      POSTGRES_DB: beastmovies
      POSTGRES_USER: beastuser
      POSTGRES_PASSWORD: beastpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U beastuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # For local development:
    build: ./backend

    # For production - choose one:
    # Docker Hub:
    # image: YOUR_DOCKER_USERNAME/beast-movies-backend:latest
    # GitHub Container Registry:
    # image: ghcr.io/ibrahimfattah/beast-movies/backend:latest

    container_name: beastmovies-backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      JWT_SECRET: your-secret-key-here-change-in-production
      PORT: 8085
      #BCRYPT_ROUNDS: 10
      #NODE_ENV: production
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    # For local development:
    build:
      context: .
      args:
        VITE_TMDB_API_KEY: ${VITE_TMDB_API_KEY}
        VITE_TMDB_BASE_URL: https://api.themoviedb.org/3
        VITE_TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p

    # For production - choose one:
    # Docker Hub:
    # image: YOUR_DOCKER_USERNAME/beast-movies-frontend:latest
    # GitHub Container Registry:
    # image: ghcr.io/ibrahimfattah/beast-movies/frontend:latest

    container_name: beastmovies-frontend
    ports:
      - "3005:80"
    depends_on:
      - backend

volumes:
  postgres_data:
