name: Deploy to Server

on:
  push:
    tags:
      -  "dev-*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USR_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/ibrahimfattah/beast-movies/backend:latest
            ghcr.io/ibrahimfattah/beast-movies/backend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/backend:latest
          cache-to: type=inline
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_TMDB_API_KEY=${{ secrets.VITE_TMDB_API_KEY }}
            VITE_TMDB_BASE_URL=https://api.themoviedb.org/3
            VITE_TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p
          tags: |
            ghcr.io/ibrahimfattah/beast-movies/frontend:latest
            ghcr.io/ibrahimfattah/beast-movies/frontend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:latest
          cache-to: type=inline

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to app directory
            cd /root/app-deployment || exit 1

            # pruning
            docker container prune -a -f
            docker image prune -a -f
            docker system prune -a -f

            
            # Pull latest changes
            # git pull origin main
            
            docker stop beastmovies-backend || true
            docker rm beastmovies-backend  || true
            
            docker stop beastmovies-frontend  || true
            docker rm beastmovies-frontend || true           
            
            echo "Deploying to dev environment ..."
            docker login ghcr.io -u ${{ github.actor }} --password "${{ secrets.USR_TOKEN }}"

            
            # Pull latest Docker images
            docker pull ghcr.io/ibrahimfattah/beast-movies/backend:latest
            docker pull ghcr.io/ibrahimfattah/beast-movies/frontend:latest
            
            /root/app-deployment/load-env.sh
